### ISSUE TITLE
Proposal: Add commas between channel suggestions

### ISSUE THREAD

**Issue by jasonblais** [jespino/mattermost-plugin-recommend#10]
Proposal: Add commas between channel suggestions. This makes it more clear what the channels are (e.g. see below where three channels are listed, but it's not clear what the names are).

Another addition, either here or separately, is adding the channel links (`~`). In the attached, the suggestions would then be `~Plugin: Todo, ~Mobile Plugins, ~/autocomplete .`

![image](https://user-images.githubusercontent.com/13119842/91853251-ed797700-ec2f-11ea-8dfc-1e4907c6c08c.png)

**Comment by jespino** [comment]
Done!
