### ISSUE TITLE
The bot recommends channels that don't exist

### ISSUE THREAD

**Issue by muratbayan** [jespino/mattermost-plugin-recommend#6]
I just got my first recommendation on the community server today and one of the channels was a guid, which led to a channel that "doesn't exist or was removed".
See screenshot below.

![image](https://user-images.githubusercontent.com/6051508/89439748-89ec4e80-d742-11ea-9beb-49c0c0c922e6.png)

Is that something that has to do with filtering the channels when generating recommendations?

**Comment by jespino** [comment]
Actually it exists but is a archived channel. I have to check it out.

**Comment by jespino** [comment]
@muratbayan this is already fixed in the new 0.0.3 release.
