### ISSUE TITLE
Rename the Plugin to be more descriptive

### ISSUE THREAD

**Issue by aaronrothschild** [jespino/mattermost-plugin-recommend#9]
The plugin name isn't too recognizable.  I think a better name would be "Channel Recommender" which better encapsulates at a glance what this plugin does (it recommends to the user, other channels they might be interested in joining). 

Can we rename the plugin to be "Channel Recommender" before it is listed in the marketplace?

**Comment by jespino** [comment]
I changed the plugin name, and the bot name (not the plugin id, but that is not that important, I think).
